### ISSUE TITLE
Fent la 1a constribució a projectes OSS

### ISSUE THREAD

**Issue by ignasi35** [fullstackvalles/talks#1]
## Títol
_Fent la 1a constribució a projectes OSS_

## Descripció

Aquesta sessió presenta les particularitats de treballar en OSS en comparació amb projectes interns d'una empresa i dóna idees per a poder col.laborar. La xerrada dura uns 20 minuts i després fem un petit taller per a que cada assitent investigui opcions i presenti la seva idea per a dur a terme una contribució (o la faci allí mateix).

## Bio
_L'Ignasi trenca la CI diàriament mentre contribueix a https://www.lagomframework.com/ (i li paguen diners per fer-ho! 🎉)._

## Format
_25min de xerrada i 35min de taller_

**Comment by ignasi35** [comment]
DISCLAIMER: ja he realitzat aquesta xerrada en d'[altres meetups](https://www.meetup.com/Software-Crafters-Barcelona/events/260506417/).

**Comment by nuria-fl** [comment]
Hola @ignasi35 ! Perdona que haguem trigat tant a dir res, hem estat desconnectats per vacances!

Ens agrada molt la proposta, però l'espai on fem ara els meetups no és gaire adequat per la part de taller. Podriem esperar a trobar un espai millor (estem en ello perquè on som ara no és accessible), o bé fer només la part de xerrada. Com ho veus?

Si ho fem de cara a octubre podriem lligar-ho amb el Hacktoberfest 🚀

**Comment by ignasi35** [comment]
> Si ho fem de cara a octubre podriem lligar-ho amb el Hacktoberfest 🚀

🔝

**Comment by nuria-fl** [comment]
👏Va estar molt bé, gràcies @ignasi35 !
